blank_issues_enabled: true
contact_links:
  - name: Enapter Developers Community
    url: https://discord.gg/fjSsXCcJ3y
    about: A Discord server for questions and support related to Enapter Marketplace and Blueprints.
