name: Blueprints Linter

on:
  pull_request_target:
    branches: [main]

jobs:
  linting:
    name: Blueprints Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Get Changed Files
        id: changes
        run: |
          echo "::set-output name=changed-files::$(git diff --name-only ${{ github.event.pull_request.head.sha }} ${{ github.sha }} | xargs)"
      - name: Security Check
        run: |
          if [ ${{ github.event.pull_request.head.repo.full_name }} != ${{ github.repository }} ]; then
          if echo ${{ steps.changes.outputs.changed-files }} | grep .scripts &> /dev/null; then
          echo "::error::scripts changes is not allowed"
          exit 1
          elif echo ${{ steps.changes.outputs.changed-files }} | grep .github &> /dev/null; then
          echo "::error::workflow changes is not allowed"
          exit 1
          fi
          fi
      - name: Check Category Icon
        run: ./.scripts/category_icon_checker.sh
      - name: Get Changed Blueprints Paths
        id: paths
        run: |
          docker run --rm \
          -v "$(pwd)":/marketplace \
          -w /marketplace/ \
          golang:1.18 go run .scripts/blueprints_collector/main.go -p /marketplace ${{ steps.changes.outputs.changed-files }}
      - name: Run Linter
        run: |
          docker run --rm \
          -v "$(pwd)":/marketplace \
          -w /marketplace/ \
          --env ENAPTER_API_TOKEN=${{ secrets.ENAPTER_API_TOKEN }} \
          docker.enapter.com/tools/blueprints-linter:v0.2.0 run -g ${{ steps.paths.outputs.blueprints-paths }}
