name: Blueprints Linter

on:
  pull_request_target:
    branches: [main]

jobs:
  linting:
    name: Blueprints Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Get Changed Files
        id: changes
        run: |
          echo "::set-output name=changed-files::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.head.sha }} ${{ github.sha }} | xargs)"
      - name: Run Linter
        run: |
          docker run --rm \
          -v "$(pwd)":/marketplace \
          --env ENAPTER_API_TOKEN=${{ secrets.ENAPTER_API_TOKEN }} \
          docker.enapter.com/tools/blueprints-linter:v0.1.0 run \
          -mp /marketplace ${{ steps.changes.outputs.changed-files }}
