name: Busted

permissions: read-all

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  busted:
    name: Busted
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ‘lua’
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: 5.3

      - name: Setup ‘luarocks’
        uses: leafo/gh-actions-luarocks@v4

      - name: Run tests
        run: ./.scripts/busted.sh
