name: Lint Code Base

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_NATURAL_LANGUAGE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          YAML_CONFIG_FILE: .yamllint.yml
          LUA_CONFIG_FILE: .luacheckrc
          MARKDOWN_CONFIG_FILE: .markdownlint.yml
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: nsmak/my-action@v2
        id: hello
        with:
          who-to-greet: 'Enapter'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
